name: ${project.name}
version: ${project.version}
author: piratjsk

main: net.piratjsk.nocmds.NoCmds

commands:
  nocmds:
    aliases: nocmd
    description: With 'reload' argument allows to reload plugin configuration.

permissions:
  nocmds.bypass:
    description: Allows to use blocked commands.
    default: op
  nocmds.admin:
    description: Allows to use 'nocmds reload' and 'nocmds list' commands.
    default: op
